DAT-18: Create an executable bundle * Fix defect where bulk executor thread-pool did not shutdown when   loader completed, causing a large stall in application termination. * Fix CSVConnector to allow user-specified connector.csv.* options. * Rename binary-target.xml to binary-distro.xml since we build   multiple archives. * Rejigger --option => reference.conf mapping; remove getopt dependency * Make contact-points an option like any other; no positional args in   command line. * Document that connector.url is a required arg. * Test the output of /usr/libexec/java_home for finding Java, and test that binary exists and is executable * Add conf dir to classpath * Make bundle's top-level directory be `datastax-loader-<version>`. * Update README with tool usage info.

diff --git a/bin/datastax-loader b/bin/datastax-loader
--- a/bin/datastax-loader
+++ b/bin/datastax-loader
@@ -8,60 +8,116 @@
 function usage() {
   local BIN_NAME=`basename "$0"`
   cat << END
-Usage: $BIN_NAME <options> [contact-point1] ...
+Usage: $BIN_NAME <options>
 Options:
- -c, --connector <connector name>   Name of connector; may be the fqcn or simple name
-                                    of an implementation of the Connector interface,
-                                    or a prefix of the simple name.
-                                    Only the built-in CSVConnector is supported at
-                                    this time, so "csv" is a good value for this.
-                                    Maps to the connector.name loader setting.
- -s, --source <source url or path>  Url or file path of data to load.
-                                    Maps to the connector.url loader setting.
- -k, --keyspace <keyspace>          Keyspace into which to load data.
-                                    Maps to the schema.keyspace loader setting.
- -t, --table <table>                Table into which to load data.
-                                    Maps to the schema.table loader setting.
- -m, --mapping <mapping>            Mapping of fields in data to columns in
-                                    the database.
-                                    Maps to the schema.mapping loader setting.
-     --loader-options <options>     Extra options to send to the loader, as a
-                                    single comma-separated string.
-                                    See conf/reference.conf for details.
+ -c, --connector.name <name>       Name of connector; may be the fqcn or simple name
+                                   of an implementation of the Connector interface,
+                                   or a prefix of the simple name. Only the built-in
+                                   CSVConnector is supported at this time, so "csv"
+                                   is a good value for this.
+ -s, --connector.csv.url <source url or path>
+                                   Url or file path of data to load.
+ -k, --schema.keyspace <keyspace>  Keyspace into which to load data.
+ -t, --schema.table <table>        Table into which to load data.
+ -m, --schema.mapping <mapping>    Mapping of fields in data to columns in the database.
 
-The list of contact points maps to the driver.contactPoints loader setting.
+All arguments except connector.csv.url are optional in that values fall back to defaults
+in conf/reference.conf or are inferred from the input data. In addition, any setting
+specified in conf/reference.conf may be overridden on the command-line with a long
+option.
 
-All arguments are optional in that values fall back to defaults in conf/reference.conf
-or are inferred from the input data.
-
-NOTE: The user is free to update defaults to meet particular requirements,
-thus reducing the command-line arguments specified in invocations.
+NOTE: The user is free to update defaults in reference.conf to meet particular requirements,
+      thus reducing the command-line arguments specified in invocations.
 
 Examples:
 * Load CSV data from /opt/data/export.csv to the ks1.table1 table in a cluster with
   a localhost contact point. Field names in the data match column names in the
   table. Field names are obtained from a "header row" in the data:
 
-  $BIN_NAME -c csv -s /opt/data/export.csv -k ks1 -t table1 --loader-options "connector.header=true"
+  $BIN_NAME -c csv -s /opt/data/export.csv -k ks1 -t table1 --connector.csv.header=true
+
+* Connector-specific options like connector.csv.header are also available with a
+  shortcut that eliminates the connector-specific name from the setting name:
+
+  $BIN_NAME -c csv -s /opt/data/export.csv -k ks1 -t table1 --connector.header=true
 
 * Same as last example, but load data from a url:
-  $BIN_NAME -c csv -s https://svr/data/export.csv -k ks1 -t table1 --loader-options "connector.header=true"
+  $BIN_NAME -c csv -s https://svr/data/export.csv -k ks1 -t table1 --connector.header=true
 
 * Same as last example, but there is no header row and we specify an explicit field mapping based
   on field indices in the input:
   $BIN_NAME -c csv -s https://svr/data/export.csv -k ks1 -t table1 -m "{0=col1,1=col3}"
 
-* Same as last example, but specify a few contact points:
-  $BIN_NAME -c csv -s https://svr/data/export.csv -k ks1 -t table1 -m "{0=col1,1=col3}" 10.200.1.3 10.200.1.4
+* Same as last example, but specify a few contact points; note how the value is quoted:
+  $BIN_NAME -c csv -s https://svr/data/export.csv -k ks1 -t table1 -m "{0=col1,1=col3}" --driver.contactPoints '["10.200.1.3","10.200.1.4"]'
 
 * Same as last example, but with connector-name, keyspace, table, and mapping set in
   conf/reference.conf:
-  $BIN_NAME -s https://svr/data/export.csv 10.200.1.3 10.200.1.4
+  $BIN_NAME -s https://svr/data/export.csv --driver.contactPoints '["10.200.1.3","10.200.1.4"]'
 END
-
-  exit 1
 }
 
+# Canonicalize arguments
+# * Convert short options to long; error out if an unknown option is encountered.
+# * Handle -h / --help
+# * Error out if positional args are specified; we don't support positional args.
+function canonicalizeArgs() {
+  local STATE=GETOPT
+  while [ $# -gt 0 ] ; do
+    if [ $STATE = GETOPT ] ; then
+      # This is an option-name, "--option=value", or a simple positional arg.
+      case "$1" in
+        -h | --help | -h=* | --help=* )
+          usage
+          exit 0
+          ;;
+        --* )
+          # Could be --option=value or just --option
+          if echo "$1" | grep "=" > /dev/null 2>&1 ; then
+            # option with value
+            OPT=$(echo "$1" | sed -e 's/=.*//')
+            VAL=$(echo "$1" | sed -e 's/[^=]*=//')
+            PARSERESULT="$PARSERESULT $OPT '$VAL'"
+          else
+            # Just option; value is the next arg.
+            PARSERESULT="$PARSERESULT $1"
+            STATE=GETVAL
+          fi
+          ;;
+        -* )
+          # Short option; doesn't support =, so just add its long-option to the result
+          case "$1" in
+           -c ) LONG="--connector.name" ;;
+           -s ) LONG="--connector.url" ;;
+           -k ) LONG="--schema.keyspace" ;;
+           -t ) LONG="--schema.table" ;;
+           -m ) LONG="--schema.mapping" ;;
+           * )
+             # Unrecognized option!
+             usage
+             echo "\nUnrecognized option: $1" >&2
+             exit 1
+             ;;
+          esac
+          PARSERESULT="$PARSERESULT $LONG"
+          STATE=GETVAL
+          ;;
+        * )
+          # Simple positional arg...that's illegal
+          usage
+          echo "\nThis tool does not support positional arguments. " >&2
+          echo "'$1' is invalid or belongs to an option." >&2
+          exit 1
+          ;;
+      esac
+    else
+      # Value
+      PARSERESULT="$PARSERESULT '$1'"
+      STATE=GETOPT
+    fi
+    shift
+  done
+}
 
 #### Main logic of script ####
 
@@ -70,6 +126,8 @@ if [ -n "$JAVA_HOME" ]; then
   if [ -x "$JAVA_HOME"/bin/java ]; then
     JAVA="$JAVA_HOME"/bin/java
   fi
+elif [ -x /usr/libexec/java_home ] ; then
+  JAVA=$(/usr/libexec/java_home)/bin/java
 else
   JAVA=java
 fi
@@ -79,51 +137,34 @@ if [ -z "$JAVA" ] ; then
   exit 1
 fi
 
-# Check that gnu getopt is available.
-for i in getopt /usr/bin/getopt /opt/local/bin/getopt /usr/local/bin/getopt /usr/local/opt/gnu-getopt/bin/getopt ; do
-  if [ -f $i ] ; then
-    $i --version | grep -E "(enhanced)|(util-linux)" > /dev/null 2>&1
-    if [ $? -eq 0 ] ; then
-      # Found it!
-      GETOPT=$i
-    fi
-  fi
-done
-
-if [ -z "$GETOPT" ] ; then
-  echo "Unable to find GNU getopt. Please install it, or set your PATH to include it." >&2
-  echo "Note that some systems (Mac in particular) have a non-GNU getopt that is not compatible" >&2
-  echo "with this script." >&2
-  exit 1
-fi
-
 INSTALL_DIR=`dirname "$0"`/..
 
 # Set CLASSPATH to include all the jars in the lib dir + the conf directory
 # (which contains reference.conf).
-for i in $INSTALL_DIR/lib/*.jar ; do
+for i in $INSTALL_DIR/lib/*.jar $INSTALL_DIR/conf; do
   CLASSPATH="$CLASSPATH:$i"
 done
 
 export CLASSPATH
 
-# Parse command-line options.
+# Parse command-line args.
 
-TEMP=`$GETOPT -o "c:k:t:m:s:h" --long "connector:keyspace:,table:,mapping:,source:,help,loader-options:" -n datastax-loader -- "$@"`
-if [ $? != 0 ] ; then
-  usage
-  exit 1
-fi
-eval set -- "$TEMP"
+canonicalizeArgs "$@"
+eval set -- "$PARSERESULT"
 
-while true; do
-  case "$1" in
-    -c | --connector ) CONNECTOR="$2"; shift 2 ;;
-    -h | --help ) usage ;;
-    -- ) shift ; break ;;
-    * ) break ;;
-  esac
+while [ $# -gt 0 ] ; do
+  OPT=$(echo $1 | sed -e 's/--//')
+  VAL=$2
+  if echo $VAL | grep -E '[#:]' > /dev/null 2>&1 ; then
+    # The value has a special character in it. Quote the value.
+    VAL="\"$VAL\""
+  fi
+  if [ -n "$LOADER_CONFIG" ] ; then
+    LOADER_CONFIG="$LOADER_CONFIG,"
+  fi
+  LOADER_CONFIG="$LOADER_CONFIG$OPT=$VAL"
+  shift 2
 done
 
 # Run the tool.
-#$JAVA com.datastax.loader.engine.Main connector.name=csv 'connector.url="file:///Users/sandeeptamhankar/tmp/good.csv"' 'log.output-directory="file:///Users/sandeeptamhankar/tmp/loader"' 'connector.comment="#"' connector.header=true schema.keyspace=ks schema.table=t1 'schema.mapping={0=year,1=make,2=model,3=description,4=price}'
+$JAVA com.datastax.loader.engine.Main $LOADER_CONFIG
